.\" Manpage for co2monitor


.TH network-check 1 "September 24, 2016" "0.0.1" "network-check"


.SH NAME

network-check \- simple tool to troubleshoot network connectivity problems

.SH DESCRIPTION

.B network-check
is a simple tool to troubleshoot network connectivity problems.

.SH SEE ALSO

ping(1),ifconfig(1),dig(1),ethtool(1)

.SH AUTHOR
.B network-check
was written by Yann Buechau <yann.buechau@web.de>.
